project:
  type: website
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  sidebar:
    contents: auto
        
  navbar:
    background: primary
    search: true
    collapse-below: lg
    left:
      - text: "Foreword"
        href: preface.ipynb
      - text: "Wadhwani AI"
        menu:
          - text: "About Us"
            icon: bug
            href: https://wadhwaniai.org/blog/
          - text: "Fast.ai Forum"
            icon: chat-right-text
            href: https://wadhwaniai.org/about/
          
    right:
      - icon: github
        href: "https://github.com/WadhwaniAI"
      - icon: twitter
        href: https://twitter.com/fastdotai
        aria-label: Fast.ai Twitter


metadata-files: [nbdev.yml]